
const Admin = (()=>{
 const TOKEN='nrfx_admin_token_v18'; let content=null, portal=null;
 const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
 const api=async(path,opt={})=>{const headers={'Content-Type':'application/json',...(opt.headers||{})};const t=sessionStorage.getItem(TOKEN);if(t)headers.Authorization='Bearer '+t;const r=await fetch(path,{cache:'no-store',...opt,headers});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Request failed');return d};
 function showAuthed(v){$('[data-login]').classList.toggle('hidden',v)}
 async function load(){content=await api('/api/admin/content'); portal=await api('/api/admin/portal'); hydrate();}
 function hydrate(){const sel=$('[data-page-select]'); sel.innerHTML=Object.keys(content.pages||{}).map(k=>`<option value="${k}">${k}</option>`).join(''); fillPage(); $('[data-services-json]').value=JSON.stringify(content.collections.services||[],null,2); $('[data-learning-json]').value=JSON.stringify(content.collections.learning||[],null,2); $('[data-announcements-json]').value=JSON.stringify(portal.portal.announcements||[],null,2); $('[data-resources-json]').value=JSON.stringify(portal.portal.resources||[],null,2); $('[data-full-json]').value=JSON.stringify(content,null,2); $('[data-users]').innerHTML=(portal.users||[]).map(u=>`<div class="item"><b>${u.name}</b><br>${u.email}<br><small>${u.plan||'Client'}</small></div>`).join('')||'<p>No users yet.</p>'; $('[data-tickets]').innerHTML=(portal.portal.tickets||[]).map(t=>`<div class="item"><b>${t.subject}</b><p>${t.message}</p><small>${t.status} • ${t.createdAt}</small></div>`).join('')||'<p>No tickets yet.</p>';}
 function fillPage(){const k=$('[data-page-select]').value;const p=content.pages[k]||{};$$('[data-page-field]').forEach(i=>i.value=p[i.dataset.pageField]||'');$('[data-page-cards]').value=JSON.stringify(p.cards||[],null,2)}
 function pull(){const k=$('[data-page-select]').value;if(k){content.pages[k]=content.pages[k]||{};$$('[data-page-field]').forEach(i=>content.pages[k][i.dataset.pageField]=i.value);try{content.pages[k].cards=JSON.parse($('[data-page-cards]').value||'[]')}catch(e){throw new Error('Invalid page cards JSON')}}try{content.collections.services=JSON.parse($('[data-services-json]').value||'[]');content.collections.learning=JSON.parse($('[data-learning-json]').value||'[]');portal.portal.announcements=JSON.parse($('[data-announcements-json]').value||'[]');portal.portal.resources=JSON.parse($('[data-resources-json]').value||'[]');const full=JSON.parse($('[data-full-json]').value||'{}'); if(full.site) content=full;}catch(e){throw new Error('Invalid JSON: '+e.message)}}
 async function save(){pull();await api('/api/admin/content',{method:'PUT',body:JSON.stringify(content)});await api('/api/admin/portal',{method:'PUT',body:JSON.stringify(portal)});alert('Saved to backend. Refresh website to see changes.');}
 $('[data-login-form]').addEventListener('submit',async e=>{e.preventDefault();$('[data-error]').textContent='';try{const fd=new FormData(e.target);const r=await api('/api/auth/login',{method:'POST',body:JSON.stringify({username:fd.get('username'),password:fd.get('password')})});sessionStorage.setItem(TOKEN,r.token);showAuthed(true);await load();}catch(err){$('[data-error]').textContent=err.message}});
 $('[data-lock]').onclick=()=>{sessionStorage.removeItem(TOKEN);showAuthed(false)}; $('[data-save]').onclick=()=>save().catch(e=>alert(e.message)); $('[data-page-select]').onchange=fillPage;
 $$('.admin-nav button').forEach(b=>b.onclick=()=>{$$('.admin-nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('[data-panel]').forEach(p=>p.classList.toggle('hidden',p.dataset.panel!==b.dataset.tab));});
 (async()=>{if(sessionStorage.getItem(TOKEN)){showAuthed(true);try{await load()}catch(e){sessionStorage.removeItem(TOKEN);showAuthed(false)}}})();
})();
