(function(){
const TOKEN='nrfx_admin_token_v19';let token=sessionStorage.getItem(TOKEN);let db=null;const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function esc(v){return String(v||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
async function api(path,opt={}){const headers={...(opt.headers||{})};if(opt.body&&!headers['Content-Type'])headers['Content-Type']='application/json';if(token)headers.Authorization='Bearer '+token;const r=await fetch(path,{...opt,headers,cache:'no-store'});let d={};try{d=await r.json()}catch(e){}if(!r.ok)throw new Error(d.error||d.detail||'Request failed');return d}
function setByPath(obj,path,value){const parts=path.split('.');let cur=obj;while(parts.length>1){const k=parts.shift();cur[k]=cur[k]||{};cur=cur[k]}cur[parts[0]]=value}
function getByPath(obj,path){return path.split('.').reduce((a,k)=>a&&a[k],obj)||''}
async function login(username,password){const d=await api('/api/auth/login',{method:'POST',body:JSON.stringify({username,password})});token=d.token;sessionStorage.setItem(TOKEN,token);await load();$('[data-login]').classList.add('hidden')}
async function load(){const content=await api('/api/admin/content');const portal=await api('/api/admin/portal');db={content,portal:portal.portal,users:portal.users||[],leads:portal.leads||[]};hydrate()}
function hydrate(){ $$('[data-path]').forEach(i=>{i.value=getByPath(db,i.dataset.path)});$('[data-json-editor]').value=JSON.stringify(db.content,null,2);renderServices();renderLearning();renderResources();renderTickets();renderUsers();}
function saveFields(){ $$('[data-path]').forEach(i=>setByPath(db,i.dataset.path,i.value));try{db.content=JSON.parse($('[data-json-editor]').value||JSON.stringify(db.content))}catch(e){} }
async function save(){saveFields();await api('/api/admin/content',{method:'PUT',body:JSON.stringify(db.content)});await api('/api/admin/portal',{method:'PUT',body:JSON.stringify({portal:db.portal,leads:db.leads})});alert('Saved to Netlify Blobs. Refresh the public site/portal to see changes.')}
function renderServices(){const el=$('[data-services-editor]');if(!el)return;const list=db.content.collections.services||[];el.innerHTML=list.map((s,i)=>`<div class="row"><div><b>${esc(s.title)}</b><small class="muted">${esc(s.body)}</small></div><button class="btn ghost small" data-edit-service="${i}">Edit</button><button class="btn ghost small danger" data-del-service="${i}">Delete</button></div>`).join('')}
function renderLearning(){const el=$('[data-learning-editor]');if(!el)return;const list=db.content.collections.learning||[];el.innerHTML=list.map((s,i)=>`<div class="row"><div><b>${esc(s.title)}</b><small class="muted">${esc(s.body)}</small></div><button class="btn ghost small" data-edit-learning="${i}">Edit</button><button class="btn ghost small danger" data-del-learning="${i}">Delete</button></div>`).join('')}
function renderResources(){const el=$('[data-resources-list]');if(!el)return;const list=db.portal.resources||[];el.innerHTML=list.map((r,i)=>`<div class="row"><div><b>${esc(r.title)}</b><small class="muted">${esc(r.type)} • ${esc(r.url||r.fileName||'No URL')}</small></div><a class="btn ghost small" target="_blank" href="${r.fileDataUrl||r.url||'#'}">Open</a><button class="btn ghost small danger" data-del-resource="${i}">Delete</button></div>`).join('')||'<p class="muted">No resources yet.</p>'}
function renderTickets(){const el=$('[data-tickets-list]');if(!el)return;const list=db.portal.tickets||[];el.innerHTML=list.map((t,i)=>`<article class="ticket-card"><b>${esc(t.subject)}</b><p>${esc(t.message)}</p><p class="muted">${esc(t.email||t.userEmail||t.userId||'client')} • ${esc(t.createdAt)}</p><div class="list-actions"><select data-ticket-status="${i}"><option ${t.status==='Open'?'selected':''}>Open</option><option ${t.status==='In review'?'selected':''}>In review</option><option ${t.status==='Resolved'?'selected':''}>Resolved</option><option ${t.status==='Closed'?'selected':''}>Closed</option></select><button class="btn ghost small danger" data-del-ticket="${i}">Delete</button></div></article>`).join('')||'<p class="muted">No tickets yet.</p>'}
function renderUsers(){const el=$('[data-users-list]');if(!el)return;const total=(db.portal.resources||[]).length;el.innerHTML=(db.users||[]).map(u=>{const done=(u.completedResources||[]).length;const pct=total?Math.round(done/total*100):0;return `<div class="row"><div><b>${esc(u.email)}</b><small class="muted">${esc(u.plan||'Client')} • ${done}/${total} resources completed • ${pct}%</small></div><span class="pill">${esc(u.id).slice(0,8)}</span><span class="pill">${pct}% progress</span></div>`}).join('')||'<p class="muted">No registered clients yet.</p>'}
function addService(){db.content.collections.services.unshift({title:'New service',body:'Service description',icon:'line-chart',image:'nrfx-service-tradingview.png',cta:'Explore'});renderServices();$('[data-json-editor]').value=JSON.stringify(db.content,null,2)}
function addLearning(){db.content.collections.learning.unshift({title:'New module',body:'Module description'});renderLearning();$('[data-json-editor]').value=JSON.stringify(db.content,null,2)}
function editItem(type,i){const arr=type==='service'?db.content.collections.services:db.content.collections.learning;const item=arr[i];const title=prompt('Title',item.title);if(title===null)return;const body=prompt('Description',item.body);if(body===null)return;item.title=title;item.body=body;if(type==='service'){item.icon=prompt('Icon / emoji',item.icon||'✦')||item.icon;item.image=prompt('Image filename or URL',item.image||'nrfx-service-tradingview.png')||item.image;item.cta=prompt('CTA',item.cta||'Explore')||item.cta}hydrate()}
async function fileToDataUrl(file){return await new Promise((res,rej)=>{const fr=new FileReader();fr.onload=()=>res(fr.result);fr.onerror=rej;fr.readAsDataURL(file)})}
$('[data-login-form]')?.addEventListener('submit',async e=>{e.preventDefault();$('[data-login-error]').textContent='';const f=new FormData(e.currentTarget);try{await login(f.get('username'),f.get('password'))}catch(err){$('[data-login-error]').textContent=err.message}})
$$('[data-nav]').forEach(b=>b.addEventListener('click',()=>{$$('[data-nav]').forEach(x=>x.classList.toggle('active',x===b));$$('[data-panel]').forEach(p=>p.classList.toggle('hidden',p.dataset.panel!==b.dataset.nav));$('[data-title]').textContent=b.textContent}))
$('[data-save]')?.addEventListener('click',save);$('[data-lock]')?.addEventListener('click',()=>{sessionStorage.removeItem(TOKEN);location.reload()});$('[data-export]')?.addEventListener('click',()=>{const blob=new Blob([JSON.stringify(db,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='noriskfx-admin-export.json';a.click()});$('[data-add-service]')?.addEventListener('click',addService);$('[data-add-learning]')?.addEventListener('click',addLearning);
document.addEventListener('click',async e=>{const t=e.target;if(t.dataset.editService)editItem('service',Number(t.dataset.editService));if(t.dataset.editLearning)editItem('learning',Number(t.dataset.editLearning));if(t.dataset.delService){db.content.collections.services.splice(Number(t.dataset.delService),1);hydrate()}if(t.dataset.delLearning){db.content.collections.learning.splice(Number(t.dataset.delLearning),1);hydrate()}if(t.dataset.delResource){db.portal.resources.splice(Number(t.dataset.delResource),1);renderResources()}if(t.dataset.delTicket){db.portal.tickets.splice(Number(t.dataset.delTicket),1);renderTickets()}if(t.matches('[data-add-resource]')){const file=$('[data-resource-file]').files[0];const r={id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),title:$('[data-resource-title]').value||'New resource',type:$('[data-resource-type]').value,body:$('[data-resource-body]').value,url:$('[data-resource-url]').value,createdAt:new Date().toISOString()};if(file){if(file.size>6*1024*1024){alert('File too large for JSON storage. Use a URL for files above 6MB.');return}r.fileName=file.name;r.size=(file.size/1024/1024).toFixed(2)+' MB';r.fileDataUrl=await fileToDataUrl(file)}db.portal.resources.unshift(r);['[data-resource-title]','[data-resource-body]','[data-resource-url]'].forEach(s=>$(s).value='');$('[data-resource-file]').value='';renderResources()}})
document.addEventListener('change',e=>{if(e.target.dataset.ticketStatus){db.portal.tickets[Number(e.target.dataset.ticketStatus)].status=e.target.value}})
if(token){load().then(()=>{$('[data-login]').classList.add('hidden')}).catch(()=>{sessionStorage.removeItem(TOKEN)})}
})();
