
const crypto = require('crypto');
let connectLambda, getStore;
try { ({ connectLambda, getStore } = require('@netlify/blobs')); } catch(e) { connectLambda = null; getStore = null; }
const STORE_NAME = process.env.BLOB_STORE || 'noriskfx-v18';
const DB_KEY = 'database.json';
const ADMIN_USER = process.env.ADMIN_USER || 'admin';
const ADMIN_PASSWORD = process.env.ADMIN_PASSWORD || '';
const JWT_SECRET = process.env.JWT_SECRET || '';
const JWT_EXPIRES_SECONDS = Number(process.env.JWT_EXPIRES_SECONDS || 60 * 60 * 8);
const API_VERSION = 'v18-institutional-portal';
function now(){return new Date().toISOString()}
function id(){return crypto.randomUUID ? crypto.randomUUID() : `id-${Date.now()}-${Math.random().toString(16).slice(2)}`}
function clone(v){return JSON.parse(JSON.stringify(v||{}))}
function json(statusCode, data){return {statusCode,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'},body:JSON.stringify(data)}}
function body(event){try{return JSON.parse(event.isBase64Encoded?Buffer.from(event.body||'','base64').toString('utf8'):(event.body||'{}'))}catch(e){return {}}}
function safe(a,b){const A=Buffer.from(String(a||'')),B=Buffer.from(String(b||''));return A.length===B.length && crypto.timingSafeEqual(A,B)}
function b64(v){return Buffer.from(v).toString('base64url')}
function sign(payload){if(!JWT_SECRET) throw new Error('JWT_SECRET missing');const data=b64(JSON.stringify({...payload,exp:Math.floor(Date.now()/1000)+JWT_EXPIRES_SECONDS}));const sig=crypto.createHmac('sha256',JWT_SECRET).update(data).digest('base64url');return `${data}.${sig}`}
function verify(token){if(!JWT_SECRET) throw new Error('JWT_SECRET missing');if(!token||!token.includes('.'))throw new Error('Missing token');const [data,sig]=token.split('.');const expected=crypto.createHmac('sha256',JWT_SECRET).update(data).digest('base64url');if(!safe(sig,expected))throw new Error('Invalid token');const p=JSON.parse(Buffer.from(data,'base64url').toString('utf8'));if(!p.exp||p.exp<Math.floor(Date.now()/1000))throw new Error('Expired token');return p}
function auth(event, role){const h=event.headers.authorization||event.headers.Authorization||'';const user=verify(h.startsWith('Bearer ')?h.slice(7):''); if(role&&user.role!==role) throw new Error('Unauthorized'); return user}
function hashPassword(password, salt=crypto.randomBytes(16).toString('hex')){const hash=crypto.pbkdf2Sync(String(password),salt,120000,32,'sha256').toString('hex');return `${salt}:${hash}`}
function checkPassword(password, stored){if(!stored||!stored.includes(':'))return false;const [salt,hash]=stored.split(':');return safe(hashPassword(password,salt).split(':')[1],hash)}
const defaultContent = {
 site:{home:{hero:{title:'واجهة أدوات تشبه غرف التداول الاحترافية.',lead:'استخدم لوحات متابعة واضحة، تنبيهات منظمة، وخطوات عملية تربط التحليل بإدارة المخاطر بدل الاعتماد على العشوائية.'},stats:{support:{value:'24/7',label:'دعم وقنوات تواصل'},services:{value:'6+',label:'خدمات متخصصة'},partners:{value:'12',label:'شريك ومنصة'},trust:{value:'100%',label:'محتوى توعوي'}},institutional:{title:'من موقع خدمات إلى تجربة قرار احترافية.',lead:'واجهة أهدأ، زجاجية، واضحة، ومهيأة لتوسّع كامل عبر الأدمن وبوابة العملاء.'},ultra:{title:'الثقة قبل البيع. الوضوح قبل القرار.',lead:'مسارات واضحة، إفصاحات ظاهرة، لغة هادئة، ونقاط قرار تساعد الزائر يفهم الخدمة قبل التواصل.'},services:{title:'كل ما يحتاجه المتداول داخل تجربة واحدة.'},calendar:{title:'الأجندة الاقتصادية المباشرة.',lead:'جدول أسبوعي مباشر من Tradays / MQL5 للتوعية ومتابعة الأخبار الاقتصادية، وليس توصية مالية.'},learning:{title:'تعلّم. طبّق. طوّر.'},portal:{title:'تجربة خاصة لكل عميل.',lead:'لوحة دخول، موارد، ملفات، إشعارات، ودعم مباشر — كلها قابلة للإدارة من الأدمن.'}}},
 collections:{services:[{title:'مؤشرات TradingView',body:'مؤشرات احترافية وتنبيهات ذكية تساعدك تقرأ السوق بوضوح.',icon:'line-chart',cta:'اكتشف الخدمة'},{title:'روبوتات MT4/MT5',body:'أتمتة تداول مصممة بانضباط: قواعد دخول وخروج وإدارة مخاطرة.',icon:'workflow',cta:'اكتشف الخدمة'},{title:'الأكاديمية',body:'مسار تعليمي عملي من الأساسيات إلى بناء خطة تداول.',icon:'graduation-cap',cta:'اكتشف الخدمة'},{title:'تحليل الأسواق',body:'قراءة منظمة للأسواق الرئيسية مع مستويات وسيناريوهات.',icon:'bar-chart',cta:'اكتشف الخدمة'},{title:'إدارة المخاطر',body:'أدوات وقواعد لضبط حجم الصفقة ونسبة المخاطرة.',icon:'shield-check',cta:'اكتشف الخدمة'},{title:'مجتمع المتداولين',body:'مساحة منظمة للنقاش، الأسئلة، وتبادل الخبرات.',icon:'users',cta:'اكتشف الخدمة'}],learning:[{title:'المفاهيم الأساسية',body:'تعلم المصطلحات وأنواع الأسواق ومنطق الحركة السعرية.'},{title:'التحليل الفني',body:'قراءة الشموع، المستويات، الاتجاه، والزخم بوضوح.'},{title:'إدارة المخاطر',body:'بناء خطة تحدد حجم الصفقة والحد الأقصى للخسارة.'},{title:'التطبيق العملي',body:'تحويل المعرفة إلى روتين تداول قابل للقياس.'}]},
 pages:{}
};
const pageNames = {services:'الخدمات',academy:'الأكاديمية',tradingview:'مؤشرات TradingView',bots:'روبوتات MT4/MT5',market:'تحليل الأسواق',risk:'إدارة المخاطر',community:'مجتمع المتداولين',legal:'المركز القانوني'};
for (const [slug,title] of Object.entries(pageNames)) defaultContent.pages[slug] = {title,lead:'صفحة قابلة للإدارة بالكامل من لوحة الأدمن.',secondaryTitle:'تجربة أوضح، إدارة أسهل، وشفافية أعلى.',secondaryLead:'يمكنك تعديل العنوان، النصوص، والبطاقات من الأدمن.',cards: clone(defaultContent.collections.services).slice(0,3)};
function defaultDb(){return {content:clone(defaultContent),portal:{announcements:[{id:id(),title:'Welcome to No Risk FX Portal',body:'Your dashboard is ready. Resources and updates appear here.',date:now()}],resources:[{id:id(),title:'Risk management checklist',type:'PDF',url:'risk-disclosure.html'},{id:id(),title:'Weekly market routine',type:'Guide',url:'academy.html'}],tickets:[]},users:[],leads:[],updatedAt:now(),version:18}}
async function store(event){ if(connectLambda) connectLambda(event); return getStore ? getStore({name:STORE_NAME,consistency:'strong'}) : null }
async function readDb(event){let db=null; try{const s=await store(event); if(s) db=await s.get(DB_KEY,{type:'json'});}catch(e){} if(!db) db=global.__NRFX_DB||defaultDb(); db.content={...clone(defaultContent),...clone(db.content||{})}; return db}
async function writeDb(event,db){db.updatedAt=now();db.version=18;try{const s=await store(event); if(s) await s.setJSON(DB_KEY,db)}catch(e){} global.__NRFX_DB=db; return db}
function route(event){let p=event.path||'/';p=p.replace(/^\/\.netlify\/functions\/api\/?/,'/').replace(/^\/api\/?/,'/'); if(!p.startsWith('/'))p='/'+p; return p.replace(/\/+$/,'')||'/'}
exports.handler = async (event)=>{const method=event.httpMethod||'GET', path=route(event); if(method==='OPTIONS')return json(204,{}); try{
 if(method==='GET'&&path==='/health') return json(200,{ok:true,service:'No Risk FX v18 API',version:API_VERSION,storage:getStore?'netlify-blobs':'memory',adminPasswordFromEnv:Boolean(process.env.ADMIN_PASSWORD),jwtSecretFromEnv:Boolean(process.env.JWT_SECRET),time:now()});
 if(method==='GET'&&path==='/public/content'){const db=await readDb(event); return json(200, db.content)}
 if(method==='POST'&&path==='/auth/login'){const b=body(event); if(!ADMIN_PASSWORD||!JWT_SECRET)return json(500,{error:'ADMIN_PASSWORD/JWT_SECRET not configured'}); if(String(b.username||'')!==ADMIN_USER||!safe(String(b.password||b.pin||''),ADMIN_PASSWORD)) return json(401,{error:'Invalid credentials'}); return json(200,{token:sign({sub:'admin',role:'admin',username:ADMIN_USER}),user:{username:ADMIN_USER,role:'admin'}})}
 if(method==='POST'&&path==='/client/register'){const b=body(event), db=await readDb(event); const email=String(b.email||'').toLowerCase().trim(); if(!email||!b.password)return json(400,{error:'Email and password required'}); if(db.users.some(u=>u.email===email))return json(409,{error:'User already exists'}); const user={id:id(),email,name:String(b.name||email),passwordHash:hashPassword(b.password),plan:'Client',createdAt:now()}; db.users.push(user); await writeDb(event,db); return json(200,{token:sign({sub:user.id,role:'client',email}),user:{id:user.id,email:user.email,name:user.name,plan:user.plan}})}
 if(method==='POST'&&path==='/client/login'){const b=body(event), db=await readDb(event); const email=String(b.email||'').toLowerCase().trim(); const user=db.users.find(u=>u.email===email); if(!user||!checkPassword(b.password,user.passwordHash))return json(401,{error:'Invalid credentials'}); return json(200,{token:sign({sub:user.id,role:'client',email}),user:{id:user.id,email:user.email,name:user.name,plan:user.plan}})}
 if(path.startsWith('/client/')){const u=auth(event,'client'); const db=await readDb(event); const user=db.users.find(x=>x.id===u.sub); if(!user)return json(401,{error:'User not found'}); if(method==='GET'&&path==='/client/dashboard')return json(200,{user:{id:user.id,email:user.email,name:user.name,plan:user.plan},portal:db.portal,tickets:db.portal.tickets.filter(t=>t.userId===user.id)}); if(method==='POST'&&path==='/client/tickets'){const b=body(event); const t={id:id(),userId:user.id,subject:String(b.subject||'Support request'),message:String(b.message||''),status:'Open',createdAt:now()}; db.portal.tickets.unshift(t); await writeDb(event,db); return json(200,t)} }
 if(path.startsWith('/admin')){auth(event,'admin'); const db=await readDb(event); if(method==='GET'&&path==='/admin/content')return json(200,db.content); if(method==='PUT'&&path==='/admin/content'){db.content=body(event); await writeDb(event,db); return json(200,db.content)} if(method==='GET'&&path==='/admin/portal')return json(200,{portal:db.portal,users:db.users.map(({passwordHash,...u})=>u),leads:db.leads}); if(method==='PUT'&&path==='/admin/portal'){const b=body(event); db.portal=b.portal||db.portal; db.leads=b.leads||db.leads; await writeDb(event,db); return json(200,{portal:db.portal,users:db.users.map(({passwordHash,...u})=>u),leads:db.leads})} if(method==='GET'&&path==='/admin/export')return json(200,db); }
 return json(404,{error:'Not found',path});
 }catch(e){return json(/token|unauth|expired|invalid/i.test(e.message)?401:500,{error:/token|unauth|expired|invalid/i.test(e.message)?'Unauthorized':'Server error',detail:e.message})}}
