(function(){
const TOKEN='nrfx_client_token_v20';let token=sessionStorage.getItem(TOKEN);let state=null;let activeFilter='all';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function esc(v){return String(v||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
async function api(path,opt={}){const headers={...(opt.headers||{})};if(opt.body&&!headers['Content-Type'])headers['Content-Type']='application/json';if(token)headers.Authorization='Bearer '+token;const r=await fetch(path,{...opt,headers,cache:'no-store'});let d={};try{d=await r.json()}catch(e){}if(!r.ok)throw new Error(d.error||d.detail||'Request failed');return d}
function showApp(on){$('[data-login-view]').classList.toggle('hidden',on);$('[data-app-view]').classList.toggle('hidden',!on)}
async function login(mode,email,password){const data=await api(mode==='register'?'/api/client/register':'/api/client/login',{method:'POST',body:JSON.stringify({email,password})});token=data.token;sessionStorage.setItem(TOKEN,token);await loadDashboard()}
async function loadDashboard(){state=await api('/api/client/dashboard');showApp(true);$('[data-client-email]').textContent=state.user.email;renderAnnouncements();renderResources();renderTickets();initPortalTradingView()}
function renderAnnouncements(){const el=$('[data-announcements]');if(!el)return;el.innerHTML=(state.portal.announcements||[]).slice(0,4).map(a=>`<div class="announcement"><b>${esc(a.title)}</b><p>${esc(a.body)}</p><small>${esc((a.date||'').slice(0,10))}</small></div>`).join('')||'<p class="muted">No announcements yet.</p>'}
function resLink(r){return r.fileDataUrl||r.url||'#'}
function renderResources(){const q=($('[data-resource-search]')?.value||'').toLowerCase();const items=(state.portal.resources||[]).filter(r=>(activeFilter==='all'||r.type===activeFilter)&&(!q||JSON.stringify(r).toLowerCase().includes(q)));const el=$('[data-resources]');if(!el)return;el.innerHTML=items.map((r,i)=>`<article class="resource-card"><span class="tag">${esc(r.type||'Guide')}</span><h3>${esc(r.title)}</h3><p>${esc(r.body||r.description||'Premium No Risk FX client resource.')}</p><div class="resource-meta"><small>${esc(r.size||r.level||'Client resource')}</small><a class="btn ghost small" target="_blank" href="${resLink(r)}">${r.type==='PDF'?'Download':'Open'} ↗</a></div></article>`).join('')||'<div class="dash-card">No resources available yet.</div>'}
function renderTickets(){const el=$('[data-ticket-list]');if(!el)return;el.innerHTML='<h3>Your tickets</h3>'+((state.tickets||[]).map(t=>`<article class="ticket"><div><b>${esc(t.subject)}</b><p>${esc(t.message)}</p></div><span class="badge">${esc(t.status)}</span><small>${esc((t.createdAt||'').replace('T',' ').slice(0,16))}</small></article>`).join('')||'<p class="muted">No tickets yet.</p>')}
function addTvWidget(target,src,config){const el=$(target);if(!el||el.dataset.loaded)return;el.dataset.loaded='1';el.innerHTML='<div class="tradingview-widget-container"><div class="tradingview-widget-container__widget"></div></div>';const holder=el.querySelector('.tradingview-widget-container');const sc=document.createElement('script');sc.type='text/javascript';sc.async=true;sc.src=src;sc.text=JSON.stringify(config);holder.appendChild(sc)}
function initPortalTradingView(){addTvWidget('[data-portal-tv-ticker]','https://s3.tradingview.com/external-embedding/embed-widget-ticker-tape.js',{symbols:[{proName:'OANDA:XAUUSD',description:'Gold'},{proName:'FX:EURUSD',description:'EUR/USD'},{proName:'BITSTAMP:BTCUSD',description:'Bitcoin'},{proName:'NASDAQ:NDX',description:'US100'}],showSymbolLogo:true,colorTheme:'dark',isTransparent:true,displayMode:'adaptive',locale:'en'});addTvWidget('[data-portal-tv-chart]','https://s3.tradingview.com/external-embedding/embed-widget-symbol-overview.js',{symbols:[["OANDA:XAUUSD|1D"],["FX:EURUSD|1D"],["BITSTAMP:BTCUSD|1D"],["NASDAQ:NDX|1D"]],chartOnly:false,width:'100%',height:'100%',locale:'en',colorTheme:'dark',autosize:true,showVolume:false,showMA:false,hideDateRanges:false,hideMarketStatus:false,hideSymbolLogo:false,scalePosition:'right',scaleMode:'Normal',fontFamily:'Inter, sans-serif',fontSize:'12',noTimeScale:false,valuesTracking:'1',changeMode:'price-and-percent',chartType:'candlesticks',lineType:0,dateRanges:['1d|1','1m|30','3m|60','12m|1D','all|1M']})}
$$('[data-nav]').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();const p=b.dataset.nav;$$('[data-panel]').forEach(x=>x.classList.toggle('hidden',x.dataset.panel!==p));$$('.portal-side [data-nav]').forEach(x=>x.classList.toggle('active',x.dataset.nav===p));location.hash=p}))
$$('.tabs button').forEach(b=>b.addEventListener('click',()=>{activeFilter=b.dataset.filter;$$('.tabs button').forEach(x=>x.classList.toggle('active',x===b));renderResources()}));$('[data-resource-search]')?.addEventListener('input',renderResources);
$('[data-client-auth]')?.addEventListener('submit',async e=>{e.preventDefault();$('[data-auth-error]').textContent='';const f=new FormData(e.currentTarget);try{await login('login',f.get('email'),f.get('password'))}catch(err){$('[data-auth-error]').textContent=err.message}});
$('[data-register]')?.addEventListener('click',async()=>{const f=new FormData($('[data-client-auth]'));$('[data-auth-error]').textContent='';try{await login('register',f.get('email'),f.get('password'))}catch(err){$('[data-auth-error]').textContent=err.message}})
$('[data-ticket-form]')?.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const payload={subject:f.get('subject'),message:f.get('message')};try{const t=await api('/api/client/tickets',{method:'POST',body:JSON.stringify(payload)});state.tickets.unshift(t);renderTickets();e.currentTarget.reset();$('[data-ticket-status]').textContent='Ticket submitted to admin inbox.';try{const formData=new URLSearchParams();formData.append('form-name','nrfx-support-ticket');formData.append('email',state.user.email);formData.append('subject',payload.subject);formData.append('message',payload.message);fetch('/',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:formData.toString()}).catch(()=>{})}catch(_){}}catch(err){$('[data-ticket-status]').textContent=err.message}})
$('[data-logout]')?.addEventListener('click',()=>{sessionStorage.removeItem(TOKEN);token=null;showApp(false)});
if(token){loadDashboard().catch(()=>{sessionStorage.removeItem(TOKEN);showApp(false)})}else showApp(false);
})();
