(function(){
const serviceImages=['nrfx-service-tradingview.png','nrfx-service-mt5.png','nrfx-service-community.png','nrfx-service-risk.png','nrfx-service-analysis.png','nrfx-service-academy.png'];
const fallback={collections:{services:[
{title:'مؤشرات TradingView',body:'مؤشرات احترافية وتنبيهات ذكية تساعدك تقرأ السوق بوضوح وتحوّل الفكرة إلى خطة قابلة للتنفيذ.',icon:'line-chart',image:'nrfx-service-tradingview.png',cta:'استكشف المؤشرات',link:'tradingview-indicators.html'},
{title:'أتمتة MT4 / MT5',body:'روبوتات تداول وخبراء مستشارين لأتمتة الاستراتيجيات، قواعد دخول وخروج، وإدارة مخاطرة منضبطة.',icon:'bot',image:'nrfx-service-mt5.png',cta:'اكتشف حلول الأتمتة',link:'mt4-mt5-bots.html'},
{title:'مجتمع المتداولين',body:'مساحة منظمة للنقاش وتبادل الخبرات، طرح الأسئلة، ومتابعة التحديثات ضمن بيئة واعية ومهنية.',icon:'users',image:'nrfx-service-community.png',cta:'انضم للمجتمع',link:'trader-community.html'},
{title:'إدارة المخاطر',body:'أدوات لحساب المخاطر، حجم الصفقات، نسبة العائد إلى المخاطرة، وحدود الخسارة قبل أي قرار.',icon:'shield-check',image:'nrfx-service-risk.png',cta:'احسب مخاطرك',link:'risk-management.html'},
{title:'تحليل الأسواق',body:'قراءة منظمة للأسواق الرئيسية مع مستويات مهمة، سيناريوهات، وتحديثات توعوية تساعدك تشتغل بخطة.',icon:'bar-chart',image:'nrfx-service-analysis.png',cta:'عرض التحليلات',link:'market-analysis.html'},
{title:'أكاديمية No Risk FX',body:'مسار تعليمي احترافي من الأساسيات إلى التطبيق، مع دروس، موارد، وتمارين عملية داخل البوابة.',icon:'graduation-cap',image:'nrfx-service-academy.png',cta:'ابدأ التعلم الآن',link:'academy.html'}],learning:[
{title:'المفاهيم الأساسية',body:'تعلم المصطلحات، أنواع الأسواق، ومنطق الحركة السعرية.',icon:'book-open',progress:'100%'},
{title:'التحليل الفني',body:'قراءة الشموع، المستويات، الاتجاه، والزخم بوضوح.',icon:'candles',progress:'75%'},
{title:'إدارة المخاطر',body:'بناء خطة تحدد حجم الصفقة والحد الأقصى للخسارة.',icon:'shield-check',progress:'50%'},
{title:'التطبيق العملي',body:'تحويل المعرفة إلى روتين تداول قابل للقياس.',icon:'target',progress:'قيد التقدم'}]}};
function esc(v){return String(v||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
async function load(){try{const r=await fetch('/api/public/content',{cache:'no-store'});if(r.ok)return await r.json()}catch(e){}return fallback}
const icons={
'graduation-cap':'<svg viewBox="0 0 24 24"><path d="M22 10 12 5 2 10l10 5 10-5Z"/><path d="M6 12v5c3 2 9 2 12 0v-5"/><path d="M22 10v6"/></svg>',
'workflow':'<svg viewBox="0 0 24 24"><rect x="3" y="3" width="6" height="6" rx="2"/><rect x="15" y="3" width="6" height="6" rx="2"/><rect x="9" y="15" width="6" height="6" rx="2"/><path d="M9 6h6M6 9v3a3 3 0 0 0 3 3M18 9v3a3 3 0 0 1-3 3"/></svg>',
'line-chart':'<svg viewBox="0 0 24 24"><path d="M3 19h18"/><path d="M5 16l4-5 4 3 6-8"/><path d="M17 6h2v2"/></svg>',
'users':'<svg viewBox="0 0 24 24"><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.87"/><path d="M16 3.13a4 4 0 0 1 0 7.75"/></svg>',
'shield-check':'<svg viewBox="0 0 24 24"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10Z"/><path d="M9 12l2 2 4-5"/></svg>',
'bar-chart':'<svg viewBox="0 0 24 24"><path d="M3 3v18h18"/><rect x="7" y="12" width="3" height="5"/><rect x="12" y="8" width="3" height="9"/><rect x="17" y="5" width="3" height="12"/></svg>',
'bot':'<svg viewBox="0 0 24 24"><rect x="5" y="7" width="14" height="11" rx="3"/><path d="M12 7V3"/><circle cx="9" cy="12" r="1"/><circle cx="15" cy="12" r="1"/><path d="M9 16h6"/></svg>',
'book-open':'<svg viewBox="0 0 24 24"><path d="M2 4v16c4-2 7-2 10 0V4C9 2 6 2 2 4Z"/><path d="M12 4v16c3-2 6-2 10 0V4c-4-2-7-2-10 0Z"/></svg>',
'candles':'<svg viewBox="0 0 24 24"><path d="M6 3v18M12 3v18M18 3v18"/><rect x="4" y="8" width="4" height="7" rx="1"/><rect x="10" y="5" width="4" height="9" rx="1"/><rect x="16" y="10" width="4" height="6" rx="1"/></svg>',
'target':'<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="5"/><circle cx="12" cy="12" r="1"/><path d="M16 8l4-4M20 4v4h-4"/></svg>',
'chart':'<svg viewBox="0 0 24 24"><path d="M3 19h18"/><path d="M6 16l4-4 3 3 5-7"/></svg>',
'bolt':'<svg viewBox="0 0 24 24"><path d="M13 2 3 14h8l-1 8 11-14h-8l0-6Z"/></svg>',
'headphones':'<svg viewBox="0 0 24 24"><path d="M3 18v-6a9 9 0 0 1 18 0v6"/><path d="M21 19a2 2 0 0 1-2 2h-2v-8h4v6Z"/><path d="M3 19a2 2 0 0 0 2 2h2v-8H3v6Z"/></svg>'
};
function iconMarkup(name,i){return icons[String(name||'').toLowerCase()]||['📈','🤖','👥','🛡','🔎','🎓'][i%6]}
function renderServices(items){document.querySelectorAll('[data-services-grid]').forEach(grid=>{grid.innerHTML=(items||fallback.collections.services).map((s,i)=>{const img=s.image||serviceImages[i%serviceImages.length];const link=s.link||'client-portal.html';return `<article class="card service-card real-card"><figure class="service-media"><img src="${esc(img)}" alt="${esc(s.title)} visual" loading="lazy" onerror="this.parentElement.classList.add('missing')"></figure><div class="service-content"><div class="service-title-row"><div class="mini-icon">${iconMarkup(s.icon,i)}</div><h3>${esc(s.title)}</h3></div><p>${esc(s.body)}</p><a class="service-link" href="${esc(link)}">${esc(s.cta||'اكتشف الخدمة')} →</a></div></article>`}).join('')})}
function renderLearning(items){document.querySelectorAll('[data-learning-grid]').forEach(grid=>{grid.innerHTML=(items||fallback.collections.learning).map((s,i)=>`<article class="card learning-step"><span class="pill">0${i+1}</span><div class="mini-icon">${iconMarkup(s.icon,i)}</div><h3>${esc(s.title)}</h3><p>${esc(s.body)}</p><small class="progress-pill">${esc(s.progress||'متاح')}</small></article>`).join('')})}
function addTvWidget(target,src,config){const el=document.querySelector(target);if(!el)return;el.innerHTML='<div class="tradingview-widget-container"><div class="tradingview-widget-container__widget"></div></div>';const holder=el.querySelector('.tradingview-widget-container');const sc=document.createElement('script');sc.type='text/javascript';sc.async=true;sc.src=src;sc.text=JSON.stringify(config);holder.appendChild(sc)}
function initTradingViewLive(){addTvWidget('[data-tv-ticker]','https://s3.tradingview.com/external-embedding/embed-widget-ticker-tape.js',{symbols:[{proName:'OANDA:XAUUSD',description:'Gold'},{proName:'FX:EURUSD',description:'EUR/USD'},{proName:'BITSTAMP:BTCUSD',description:'Bitcoin'},{proName:'NASDAQ:NDX',description:'US100'},{proName:'TVC:US30',description:'US30'}],showSymbolLogo:true,colorTheme:'dark',isTransparent:true,displayMode:'adaptive',locale:'en'});addTvWidget('[data-tv-overview]','https://s3.tradingview.com/external-embedding/embed-widget-symbol-overview.js',{symbols:[["OANDA:XAUUSD|1D"],["FX:EURUSD|1D"],["BITSTAMP:BTCUSD|1D"],["NASDAQ:NDX|1D"],["TVC:US30|1D"]],chartOnly:false,width:'100%',height:'100%',locale:'en',colorTheme:'dark',autosize:true,showVolume:false,showMA:false,hideDateRanges:false,hideMarketStatus:false,hideSymbolLogo:false,scalePosition:'right',scaleMode:'Normal',fontFamily:'Inter, sans-serif',fontSize:'12',noTimeScale:false,valuesTracking:'1',changeMode:'price-and-percent',chartType:'candlesticks',lineType:0,dateRanges:['1d|1','1m|30','3m|60','12m|1D','60m|1W','all|1M']})}
function decorateStaticIcons(){document.querySelectorAll('[data-lucide]').forEach((el,i)=>{el.innerHTML=iconMarkup(el.dataset.lucide,i)})}
decorateStaticIcons();initTradingViewLive();setTimeout(()=>{if(document.querySelector('[data-tv-overview]')&&!document.querySelector('[data-tv-overview] iframe'))document.body.classList.add('tv-fallback')},6500);
load().then(content=>{renderServices(content.collections&&content.collections.services);renderLearning(content.collections&&content.collections.learning);const hero=content.site&&content.site.home&&content.site.home.hero;if(hero){const title=document.querySelector('[data-cms="home.hero.title"]');const lead=document.querySelector('[data-cms="home.hero.lead"]');if(title)title.innerHTML=esc(hero.title||'').replace(/تشبه غرف التداول/g,'<span>تشبه غرف التداول</span>');if(lead)lead.textContent=hero.lead||''}})
})();
